version: "3.8"
services:
  node-app:
    container_name: node-app
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    build: .
    ports:
      - "3000:3000"
    command: nodemon index.js
    depends_on:
      - mongo
  mongo:
  container_name: mongo
  image: mongo
  volumes:
    - mongo-db:/data/db
  ports:
    - "27017:27017"

volumes:
  mongo-db: